# Recording parameters
videoFolder: "/home/michael/data" # "/mocap_data/DATA"
videoFilename: "0.mp4"
frameRate: 100
recTimeInSec: 60

# Camera parameters
cameraMake: "flir"
numCams: 1
cameraSelection: [0]
# cameraSettings: "./campy/cameras/flir/settings/BFS-U3-19S4_1616x1240_60fps_no_trigger_RGB_p6.pfs" # is this even used??
cameraNames: ['Camera1']

# Compression parameters
ffmpegLogLevel: ["quiet"]
gpuID: 0
gpuMake: "nvidia"
pixelFormatInput: "bayer_rggb8" # 'bayer_bggr8' 'rgb24'
pixelFormatOutput: "rgb0"
codec: "h264"
quality: "21"

# Display parameters
chunkLengthInSec: 30
displayFrameRate: 10
displayDownsample: 2

# Other parameters
ffmpegPath: "/home/michael/workspace/ffmpeg/ffmpeg" #[] ["/home/usr/Documents/ffmpeg/ffmpeg"]
emulate: False
frameWidth: 1616
frameHeight: 1232

# Trigger
useTrigger: False
