# Video parameters
videoFolder: "C:\\Users\\Michael\\test"
videoFilename: "0.mp4"
frameRate: 60
recTimeInSec: 60

# Camera parameters
numCams: 3
# cameraSelection: [0,1,2]
#cameraSettings: "./campy/cameras/basler/settings/acA1920-150uc_1152x1024p_100fps_trigger_RGB_p6.pfs"
cameraNames: ["cam1","cam2","cam3"]
cameraMake: "flir"
cameraTrigger: [] # Line0


# Compression parameters
ffmpegLogLevel: ["quiet","quiet","info"] # "quiet", "warning", "info"
gpuID: 0                  # -1 = CPU
gpuMake: "nvidia"         # "nvidia", "amd", "intel"                  
codec: "h264"             # "h264", "h265", or user-defined video codec
quality: "21"             # 0-55
pixelFormatInput: "bayer_rggb8" 
pixelFormatOutput: "rgb0"

# Display parameters
chunkLengthInSec: 30
displayFrameRate: 10
displayDownsample: 2

# Other parameters
ffmpegPath: [] #["/home/usr/Documents/ffmpeg/ffmpeg"]
#emulate: False
frameWidth: 1616
frameHeight: 1232